### ISSUE TITLE
Werkt niet.. 404 bij ophalen data(?)

### ISSUE THREAD

**Issue by demon326** [jjtbsomhorst/ubbgenerator#1]
Dag Jeroen,

Om te beginnen, leuk dat je de sourcecode deelt, maar het wilt niet zo goed werken bijmij.

Het zegt altijd 'no results found', of gewoon geen resultaten zonder tekst. Als ik de http headers check via firefox zie ik dat hij een 404 not found geeft bij:

https://site.be/review/api.php/movies/alien

Ik vermoed dat dit door nginx komt, maar ik ben niet zeker.

- nginx/1.10.2

- php 7.0

De redenen dat ik jouw versie, voor tweakers niet kan gebruiken is omdat ons forum een html output verwacht :)

**Comment by jjtbsomhorst** [comment]
Hoi, 

Weet je wat de foutmelding van de server is ? Oftewel in de Apache logs en PHP error logs ? 

Als je wil kan ik ook een optie toevoegen aan de bestaande om HTML te genereren. Dan moet ik alleen de diverse tags weten die mogen.

**Comment by demon326** [comment]
Ik denk dat dat misschien nog de makkelijkste optie is.

De code, in html vorm die bij ons(op basis van burning board) werkt:
http://pastebin.com/Nz2R35iu

Om het simpel te houden, de werkende tags zijn

```
- <table>
- <td>
- <tr>
- <tbody>
- <img>
- <small>
- <strong>
- <a href>
```

Gewoon de html varianten dus :)

De bedoeling is om het op https://home-theater.be/ te gebruiken, vind jouw systeem overzichtelijk

**Comment by jjtbsomhorst** [comment]
Ik heb inmiddels een update uitgevoerd op de UBB Generator. Als je deze nu opent met de url http://www.jeroensomhorst.eu/ubbgenerator/#?format=html dan zou je als je op de knop genereer opmaak hebt geklikt HTML opmaak moeten terug krijgen in plaats van UBB. 

Zou je dit kunnen/willen testen?

**Comment by jjtbsomhorst** [comment]
@demon326  zou je eventjes kunnen laten weten of dat dit voldoende is?

**Comment by demon326** [comment]
Werkt naar behoren, dank je! 
Zie https://home-theater.be/topic/13-welke-film-hebben-jullie-zopas-gezien/?pageNo=139#post45507 voor voorbeeld :)
