### ISSUE TITLE
Geen poster, terwijl er op IMDB wel eentje staat

### ISSUE THREAD

**Issue by pven** [jjtbsomhorst/ubbgenerator#2]
Zie https://gathering.tweakers.net/forum/list_message/51099605#51099605 voor wat ik bedoel. Op IMDB staat wel een poster, maar die wordt in de gegenereerde code niet gevonden.

**Comment by jjtbsomhorst** [comment]
Dit heeft er mee te maken dat ik geen gebruik maak van de imdb website. Aangezien deze geen losse api hebben en scrapen van die data niet mag. Daarom kan het voorkomen dat de api die ik gebruik (omdbapi) op het moment van ophalen nog geen poster heeft maar later nog wel. Ik zal binnenkort eens wat gaan opschonen zodat de juiste poster wordt gebruikt.
