### ISSUE TITLE
ubbgenerator vindt geen films

### ISSUE THREAD

**Issue by pven** [jjtbsomhorst/ubbgenerator#4]
Waar je ook naar zoekt, er wordt niets gevonden:
![2017-05-23 09_18_26-www jeroensomhorst eu_ubbgenerator_ _format ubb](https://cloud.githubusercontent.com/assets/671621/26342553/dc549cda-3f98-11e7-9cb9-fce4969aebad.jpg)

**Comment by jjtbsomhorst** [comment]
Bedankt voor het melden. Het lijkt erop dat er iets met de service mis is. Ik zal dit zsm oppakken

**Comment by pven** [comment]
Het werkt weer :-)
